=begin
#Sunshine Conversations API

The version of the OpenAPI document: 12.5.0

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 4.3.1
=end

module SunshineConversationsClient
  VERSION = '12.5.0'
end
